spring.application.name=backend

spring.main.banner-mode=off
#logging.level.root=WARN

# database conf
spring.datasource.url=jdbc:postgresql://localhost:5433/trainme_db
spring.datasource.username=trainme_user
spring.datasource.password=trainme_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update